#!/usr/bin/env python3

"""Usage:
   apf ls <identifier-chunk> ...
   apf validate (--list-valid | --show-errors) <identifier-chunk> ...
"""

import os, glob
import sys
from classes import ApfOwnCloudValidator, OwnCloudWebDAV
from docopt import docopt

if __name__ == '__main__':
    arguments = docopt(__doc__)

    apf_valid = ApfOwnCloudValidator()
    #apf_valid.connect(os.environ['OWNCLOUD_SSH_SERVER'], {})

    # build a set of identifiers (e.g. 'apf1-00001', 'apf1-00002', etc.) from
    # the identifier chunks (e.g. 'apf1', 'apf2', etc.) that were passed in on
    # the command line.
    #
    # examples:
    # apf ls apf1
    # apf ls apf1 apf2 apf3

    identifiers = []
    for i in range(0,len(arguments['<identifier-chunk>'])):
        identifiers.insert(i,(apf_valid.list_dir(arguments['<identifier-chunk>'][i])))

    if arguments['ls']:
        for identifier in identifiers:
            for i in identifier:
                if i.endswith('.tif'):
                    i = i[:-4]
                    sys.stdout.write(i + '\n')

    elif arguments['validate']:
        for identifier in identifiers:
            errors = apf_valid.validate(identifier)
            if arguments['--show-errors']:
                for error in errors:
                    sys.stdout.write(error)
            elif arguments['--list-valid']:
                if not errors:
                    sys.stdout.write('{}\n'.format(identifier))

 