#!/usr/bin/env python3

"""Usage:
   digcoll ls <identifier-chunk> ...
"""

import os
import sys
from classes import OwnCloudSSH, OwnCloudWebDAV
from docopt import docopt


if __name__ == '__main__':
    arguments = docopt(__doc__)

    kwargs = {
        'username': os.environ['OWNCLOUD_SSH_USERNAME'],
        'password': os.environ['OWNCLOUD_SSH_PASSWORD']
    }
    if 'SSH_PRIVATE_KEY_PATH' in os.environ:
        kwargs['key_filename'] = os.environ['SSH_PRIVATE_KEY_PATH']
    owncloud_ssh = OwnCloudSSH(os.environ['OWNCLOUD_SSH_SERVER'], kwargs)

    identifiers = set()
    for identifier_chunk in arguments['<identifier-chunk>']:
        for i in owncloud_ssh.recursive_ls(identifier_chunk):
            project = i.split('-')[0]
            if project in ('ewm', 'gms', 'mvol', 'speculum'):
                identifiers.add(i)
    identifiers = sorted(list(identifiers))

    if arguments['ls']:
        for identifier in identifiers:
            sys.stdout.write(identifier + '\n')
