#!/usr/bin/env python3

"""Usage:
   ewm crop_report <directory>
"""


import datetime
import os
import re
import statistics
import time
from docopt import docopt


def count_tifs(directory):
  return len([f for f in os.listdir(directory) if re.search('\.tif$', f)])


def get_median_mtime_diff(directory):
  mtimes = []
  for f in os.listdir(directory):
    mtimes.append(os.path.getmtime('{}/{}'.format(directory, f)))
  mtimes.sort()

  diffs = []
  m = 1
  while m < len(mtimes):
    diffs.append(mtimes[m] - mtimes[m - 1])
    m = m + 1

  return statistics.median(diffs)


if __name__=='__main__':
  arguments = docopt(__doc__)

  if arguments['crop_report']:
    for d in os.listdir(arguments['<directory>']):
      if re.match('^ewm-', d):
        try:
          masters_count = count_tifs('{}/{}/Masters'.format(
            arguments['<directory>'],
            d
          ))
          tiff_crop_count = count_tifs('{}/{}/Tiff Crop'.format(
            arguments['<directory>'],
            d
          ))
          if tiff_crop_count == 0:
            status = ''
          elif tiff_crop_count < masters_count:
            try:
              check_time = datetime.datetime.now() + datetime.timedelta(
                seconds=get_median_mtime_diff('{}/{}/Tiff Crop'.format(
                  arguments['<directory>'],
                  d
                )) * (masters_count - tiff_crop_count)
              )
              status = 'WORKING...check {}'.format(check_time.strftime('%A, %I:%M%p'))
            except statistics.StatisticsError:
              status = 'WORKING...'
          elif tiff_crop_count == masters_count:
            status = 'DONE'
          else:
            status = '?'
          print('{} {:5} {}'.format(d, masters_count, status))
        except FileNotFoundError:
          continue
