#!/usr/bin/env python3

"""Usage:
   fix_mvol_struct_txt (--fix-existing|--make-new) <identifier>

   It's common for mvol source files to omit a .struct.txt file. This script
   creates one of those files and uploads it to Owncloud via WebDAV.
"""

import csv, os, re, sys
from docopt import docopt
from io import StringIO

def get_jpeg_count(identifier):
    c = 0
    for entry in os.listdir('/data/digital_collections/IIIF/IIIF_Files/{}/JPEG'.format(identifier.replace('-', '/'))):
        if entry.endswith('.jpg'):
            c += 1
    return c

if __name__ == '__main__':
    options = docopt(__doc__)

    struct_txt_path = '/data/digital_collections/IIIF/IIIF_Files/{}/{}.struct.txt'.format(
        options['<identifier>'].replace('-', '/'), 
        options['<identifier>']
    )

    jpeg_count = get_jpeg_count(options['<identifier>'])
    objects = [str(i).zfill(8) for i in range(1, jpeg_count + 1)]

    if options['--fix-existing']:
        raise NotImplementedError

    if options['--make-new']:
        pages = [str(i) for i in range(1, jpeg_count + 1)]
        milestones = ['' for i in range(jpeg_count)]
        txt_data = 'object\tpage\tmilestone\n'
    for i in range(jpeg_count):
        txt_data = txt_data + '{}\t{}\t{}\n'.format(objects[i], pages[i], milestones[i])

    if os.path.exists(struct_txt_path):
        sys.stderr.write('{} exists!\n'.format(struct_txt_path))
        sys.exit()
    else:
        with open(struct_txt_path, 'w') as f:
            f.write(txt_data)
