#!/usr/bin/env python3

"""Usage:
   fix_mvol_dc_xml <identifier>
"""

import os, re, sys
import xml.etree.ElementTree as ElementTree
from docopt import docopt


def make_dc_title(identifier):
    """Return a title based on the identifier.

    N.B. The description for mvol-0004 says that the Daily Maroon was published
    from 1902-1942, and that it was continued by the Chicago Maroon. Title
    metadata for later years currently reads "Daily Maroon". Throw an assertion
    error if the title is not Daily Maroon, and re-evaluate this code if other
    titles appear. 

    Args:
        identifier (str): e.g. 'mvol-0001-0002-0003'

    Returns:
        str: the title for an identifier chunk like 'mvol-0004'.
    """

    identifier_chunk = '-'.join(identifier.split('-')[:2])
    titles = {
        'mvol-0004': 'Daily Maroon',
    }
    return titles[identifier_chunk]


def make_dc_date(identifier):
    """Return a date based on the identifier.

    Args:
        identifier (str): e.g. 'mvol-0004-1938-0103'

    Returns:
        str: a string, e.g. '1938-01-03'
    """

    if re.search('^mvol-0004-\d{4}-\d{4}$', identifier):
        return '{}-{}-{}'.format(
            identifier.split('-')[-2],
            identifier.split('-')[-1][:2],
            identifier.split('-')[-1][2:]
        )
    else:
        raise ValueError


def make_dc_description(identifier):
    """Return a description based on the identifier. 

    Args:
        identifier (str): e.g. 'mvol-0001-0002-0003'

    Returns:
        str: the description for an identifier chunk like 'mvol-0004'.
    """

    identifier_chunk = '-'.join(identifier.split('-')[:2])
    descriptions = {
        'mvol-0004': 'A newspaper produced by students of the University of Chicago. Published 1902-1942 and continued by the Chicago Maroon.'
    }
    return descriptions[identifier_chunk]


if __name__ == '__main__':
    options = docopt(__doc__)

    sys.stdout.write(''.join((
        '<?xml version="1.0" encoding="utf8"?>',
        '<metadata>',
        '<title>{}</title>'.format(make_dc_title(options['<identifier>'])),
        '<date>{}</date>'.format(make_dc_date(options['<identifier>'])),
        '<description>{}</description>'.format(make_dc_description(options['<identifier>'])),
        '<identifier>{}</identifier>'.format(options['<identifier>']),
        '</metadata>'
    )))
