#!/usr/bin/env python3
"""Usage:
   fix_mvol_numbered_filenames [--dry-run] <identifier> <directory>

   Rename files in mvol's ALTO, JPEG, POS and TIFF directories. The script
   renames files to an intermediate filename, composed of a timestamp in
   milliseconds, before correctly renumbering them to avoid collisions.
"""
import os, re, sys, time
from docopt import docopt

def batch_rename_mvol(directory, dry_run = True):
    """Rename files in a directory (e.g. ALTO, JPEG, TIFF, etc.)
    according to a pattern. 

    Args:
    directory (str): e.g. 'IIIF_Files/mvol/0001/0002/0003/ALTO/'
    pattern_fun: a pattern function. 
    """

    extensions = {
        'ALTO': 'xml',
        'JPEG': 'jpg',
        'POS': 'pos',
        'TIFF': 'tif',
        'XML': 'xml'
    }

    assert len(directory.split('/')) == 11

    mvol_str = '-'.join(directory.split('/')[5:9])

    extension = extensions[directory.split('/')[-2]]

    ms_time = str(int(round(time.time() * 1000)))

    source_names = sorted(os.listdir(directory))

    intermediate_names = ['{}.{}'.format(p, ms_time) for p in source_names]

    target_names = []
    for i in range(len(source_names)):
        target_names.append(
            '{}_{}.{}'.format(
                mvol_str, 
                str(i+1).zfill(4), 
                extension
            )
        )

    if set(source_names) == set(target_names):
        return

    if set(source_names).intersection(set(intermediate_names)):
        raise RuntimeError

    if set(intermediate_names).intersection(set(target_names)):
        raise RuntimeError

    for i in range(len(source_names)):
        if dry_run:
            sys.stdout.write('move {0}{1} to {0}{2}\n'.format(
                directory, 
                source_names[i], 
                intermediate_names[i]
            ))
        else:
            os.rename(directory + source_names[i], directory + intermediate_names[i])
        i = i + 1

    for i in range(len(intermediate_names)):
        if dry_run:
            sys.stdout.write('move {0}{1} to {0}{2}\n'.format(
                directory,
                intermediate_names[i],
                target_names[i]
            ))
        else:
            os.rename(directory + intermediate_names[i], directory + target_names[i])
        i = i + 1

if __name__=='__main__':
    options = docopt(__doc__)

    assert options['<identifier>'].startswith('mvol-')

    directory = '/data/digital_collections/IIIF/IIIF_Files/{}/{}/'.format(
        options['<identifier>'].replace('-', '/'), 
        options['<directory>']
    )

    if not options['<directory>'] in ('ALTO', 'JPEG', 'POS', 'TIFF', 'XML'):
        sys.stderr.write('<directory> must be one of: ALTO, JPEG, POS, TIFF, XML\n')
        sys.exit()

    try:
        batch_rename_mvol(directory, options['--dry-run'])
    except RuntimeError:
        sys.stderr.write('Could not rename {} {}.\n'.format(
            options['<identifier>'],
            options['<directory>']
        ))
        sys.exit()
