#!/usr/bin/env python3

"""Usage:
   gms ls [<identifier-chunk> ...]
   gms validate (--list-valid | --show-errors) [<identifier-chunk> ...]
"""

import os, re, sys
from classes import *
from docopt import docopt

if __name__ == '__main__':
    arguments = docopt(__doc__)

    gms_validator = GmsValidator()
    gms_validator.connect(os.environ['OWNCLOUD_SSH_SERVER'], {})

    identifiers = []
    if 'gms' in arguments['<identifier-chunk>'] or \
       len(arguments['<identifier-chunk>']) == 0:
        identifiers = sorted(
            gms_validator.cs_listdir(gms_validator.get_path('gms'))
        )
    else:
        for i in arguments['<identifier-chunk>']:
            if re.match('^gms-\d{4}$', i):
                identifiers.append(i)

    if arguments['ls']:
        for i in identifiers:
            sys.stdout.write(i + '\n')
        sys.exit()

    elif arguments['validate']:
        output = []
        for identifier in identifiers:
            errors = gms_validator.validate(identifier)
            if arguments['--show-errors']:
                output.extend(errors)
            elif arguments['--list-valid']:
                if not errors:
                    output.append(identifier)
        sys.stdout.write(''.join(output))
        sys.exit()
