#!/usr/bin/env python3

"""Usage:
   mvol check_sync (--owncloud-to-development | --owncloud-to-production) (--list-in-sync | --list-out-of-sync) <identifier-chunk> ...
   mvol csvreport <identifier-chunk> ...
   mvol ls <identifier-chunk> ...
   mvol validate (--list-valid|--show-errors) [--local-root=<path>] <identifier-chunk> ...
"""

import operator
import os
import sys
from classes import MvolValidator, XTFValidator
from docopt import docopt


if __name__ == '__main__':
    arguments = docopt(__doc__)

    mvol_valid = MvolValidator()
    if arguments['--local-root']:
        mvol_valid.set_local_root(arguments['--local-root'])
    else:
        mvol_valid.connect(os.environ['OWNCLOUD_SSH_SERVER'], {})

    if any((arguments['check_sync'],)):
        if arguments['--owncloud-to-development']:
            xtf_ssh = XTFvalidator(False)
            xtf_ssh.connect(os.environ['XTF_DEVELOPMENT_SERVER'], {})
        elif arguments['--owncloud-to-production']:
            xtf_ssh = XTFValidator(True)
            xtf_ssh.connect(os.environ['XTF_PRODUCTION_SERVER'], {})

    identifiers = set()
    for identifier_chunk in arguments['<identifier-chunk>']:
        for i in mvol_valid.recursive_ls(identifier_chunk):
            if i.startswith('mvol'):
                identifiers.add(i)
    identifiers = sorted(list(identifiers))

    if arguments['check_sync']:
        if arguments['--list-in-sync']:
            comparison = operator.le
        elif arguments['--list-out-of-sync']:
            comparison = operator.gt
        for identifier in identifiers:
            try:
                if comparison(
                    mvol_valid.get_newest_modification_time(identifier),
                    xtf_ssh.get_newest_modification_time(identifier)
                ):
                    sys.stdout.write(identifier + '\n')
            except FileNotFoundError:
                if arguments['--list-out-of-sync']: 
                    sys.stdout.write(identifier + '\n')
      
    elif arguments['csvreport']:
        # get a set of identifier_years, e.g. mvol-0004-1951.
        identifier_years = set()
        for i in identifiers:
            if not i.startswith('mvol'):
                raise NotImplementedError
            identifier_years.add('-'.join(i.split('-')[:3]))

        csv_data = {}
        for i in identifier_years:
            csv_data = {**csv_data, **mvol_valid.get_csv_data(i)}

        csv_mvols = set(csv_data.keys())
        owncloud_mvols = set(identifiers)

        csv_only = csv_mvols - owncloud_mvols
        if csv_only:
            sys.stdout.write('The following mvols are present in CSV data but not in Owncloud:\n')
            sys.stdout.write('\n'.join(sorted(csv_only)) + '\n')
        owncloud_only = owncloud_mvols - csv_mvols
        if owncloud_only:
            sys.stdout.write('The following mvols are present in Owncloud but not in CSV data:\n')
            sys.stdout.write('\n'.join(sorted(owncloud_only)) + '\n')
    elif arguments['ls']:
        for identifier in identifiers:
            sys.stdout.write(identifier + '\n')
    elif arguments['validate']:
        for identifier in identifiers:
            errors = mvol_valid.validate(identifier)
            if arguments['--show-errors']:
                for error in errors:
                    sys.stdout.write(error)
            elif arguments['--list-valid']:
                if not errors:
                    sys.stdout.write('{}\n'.format(identifier))
