#!/usr/local/bin/python3

"""put_struct_txt
   It's common for mvol source files to omit a .struct.txt file. This script
   creates one of those files and uploads it to Owncloud via WebDAV.

   Usage:
   put_struct_txt <identifier>
"""

from docopt import docopt
import os
import owncloud
import re
import sys


if __name__ == '__main__':
    arguments = docopt(__doc__)
    identifier = arguments['<identifier>']

    oc = owncloud.Client(os.environ['OWNCLOUD_WEBDAV_SERVER'])
    try:
        oc.login(
            os.environ['OWNCLOUD_WEBDAV_USERNAME'],
            os.environ['OWNCLOUD_WEBDAV_PASSWORD']
        )
    except owncloud.HTTPResponseError:
        sys.stderr.write('incorrect WebDAV password.\n')
        sys.exit()

    remote_path = 'IIIF_Files/{}/{}.struct.txt'.format(identifier.replace('-', '/'), identifier)

    try:
        oc.file_info(remote_path)
        sys.stdout.write('A .struct.txt file already exists in that location.\n')
        sys.exit()
    except owncloud.owncloud.HTTPResponseError:
        pass

    jpeg_count = 0
    for entry in oc.list('IIIF_Files/{}/JPEG'.format(identifier.replace('-', '/'))):
        if entry.get_name().startswith(identifier):
            jpeg_count = jpeg_count + 1

    txt_data = 'object\tpage\tmilestone\n'
    for i in range(1, jpeg_count + 1):
        txt_data = txt_data + '{}\t{}\n'.format(str(i).zfill(8), i)
 
    oc.put_file_contents(remote_path, txt_data)
