# Generated by Django 2.0.8 on 2018-08-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='mvolFolder',
            fields=[
                ('folder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listpage.Folder')),
                ('date', models.DateTimeField(null=True)),
                ('valid', models.NullBooleanField()),
                ('loc1', models.DateTimeField(null=True)),
                ('loc2', models.DateTimeField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listpage.mvolFolder')),
            ],
            bases=('listpage.folder',),
        ),
    ]
